"""Home page content for ja."""

HOME_JA = {'seo': {'title': 'Muhammad Rizal Muhaimin | ソフトウェアエンジニア',
         'description': 'モダンWeb開発とAndroid開発の実務経験を持ち、AI、コンピュータビジョン、自律ロボティクスへ専門性を広げているMuhammad Rizal '
                        'Muhaiminのポートフォリオです。'},
 'ui': {'skip': 'メインコンテンツへ移動',
        'nav_label': 'メインナビゲーション',
        'nav_home': 'ホーム',
        'nav_projects': 'プロジェクト',
        'nav_cv': 'CV',
        'nav_blog': 'ブログ',
        'language': '言語',
        'apply': '適用',
        'primary_actions': '主な操作',
        'view_projects': 'プロジェクトを見る',
        'download_cv': 'CVをダウンロード',
        'about_link': '自己紹介',
        'cv_note': 'CVは準備中です。承認済みPDFの公開後にCV_URLを設定します。',
        'photo_placeholder': 'プロフィール写真（準備中）',
        'project_image': 'プロジェクト画像（準備中）',
        'view_experience': '職務経歴を詳しく見る',
        'view_project': 'プロジェクトを見る',
        'read_project': 'プロジェクト詳細を見る',
        'technologies': '使用技術：',
        'career_development': 'キャリア開発',
        'career_topics': '今後注力する分野',
        'open_to_work': '意義ある仕事との出会いを歓迎します',
        'contact': 'お問い合わせ',
        'contact_note': '連絡先は準備中です。承認済みの連絡手段が決まり次第CONTACT_URLを設定します。',
        'footer': 'Muhammad Rizal Muhaimin — ソフトウェアエンジニア',
        'fallback': '指定された翻訳を利用できないため、インドネシア語で表示しています。',
        'og_alt': 'Muhammad Rizal Muhaiminのポートフォリオプレビュー',
        'error': 'エラー',
        'not_found': 'ページが見つかりません',
        'not_found_message': '指定されたページまたはリソースが見つかりません。',
        'internal_error': '内部エラー',
        'internal_error_message': '内部エラーが発生しました。',
        'request_id': 'リクエストID',
        'back_home': 'ホームへ戻る'},
 'hero': {'eyebrow': '日本在住のソフトウェアエンジニア',
          'greeting': 'はじめまして、Rizalです。',
          'headline': '信頼性と使いやすさを大切に、デジタルプロダクトを開発するソフトウェアエンジニアです。',
          'description': 'React.jsとJavaScriptを中心としたモダンWeb開発の実務経験があります。KotlinによるAndroidアプリ開発にも携わり、現在はAI、コンピュータビジョン、自律ロボティクスへ知識を広げています。',
          'photo_alt': 'Muhammad Rizal Muhaiminのプロフィール写真',
          'photo_placeholder': 'プロフィール写真（準備中）'},
 'about': {'heading': '私について',
           'paragraphs': ('インドネシア出身で、現在は日本を拠点にキャリアを築いているソフトウェアエンジニアです。約3年間のソフトウェア開発経験があり、特にReact.jsとJavaScriptを用いたWebアプリケーション開発を強みとしています。',
                          'インターン、フリーランス開発者、正社員のソフトウェアエンジニアへと経験を重ねてきました。保守しやすいUI設計、API連携、状態管理、テスト、チーム開発、要件からリリースまでの一連の工程を実務で学びました。',
                          'Web開発に加え、KotlinとJetpack '
                          'ComposeによるAndroidアプリも開発しています。今後のキャリアに向けて、Python、コンピュータビジョン、AIカメラ、ROS、SLAM、自律移動ロボットの学習を深めています。')},
 'experience': {'heading': '主な職務経験',
                'intro': '実践的なプロダクト開発、継続的な学習、国際的なチーム環境への適応を通じて培った経験です。',
                'items': ({'company': 'CBS Techno',
                           'role': 'ソフトウェアエンジニア',
                           'location': '日本',
                           'period': '現在',
                           'progression': None,
                           'highlights': ('日本のエンジニアリング環境で必要となる技術力と日本語力を向上。',
                                          '業務アプリケーション、スマートファクトリー、AIカメラ、自律ロボティクス関連技術を学習。',
                                          '研修を通じてJava Spring BootとReact.jsのスキルを強化。',
                                          '日本の職場文化、コミュニケーション、ソフトウェア開発プロセスへの理解を深化。')},
                          {'company': 'PT DAnS Multi Pro',
                           'role': 'ソフトウェアエンジニア',
                           'location': 'インドネシア・ジャカルタ',
                           'period': '2022–2025',
                           'progression': 'インターン → フリーランス開発者 → 正社員ソフトウェアエンジニア',
                           'highlights': ('React.jsとJavaScript/TypeScriptによるモダンWebアプリケーションを開発。',
                                          '再利用可能なコンポーネント、状態管理、REST API連携を担当。',
                                          '要件に応じてRedux、Zustand、Axios、React Query、Ant '
                                          'Design、Material UI、Tailwind CSSを活用。',
                                          '単体テストを実施し、Test-Driven Developmentの基礎を適用。',
                                          'コードレビュー、デバッグ、保守、デプロイ工程に参加。',
                                          'Module Federationとwebpackを用いたマイクロフロントエンドを開発。',
                                          '課題設計とライブコーディングを通じてフロントエンド候補者の評価を支援。')})},
 'projects': {'heading': '注目プロジェクト',
              'intro': 'Web、モバイル、コネクテッドシステム分野の代表的な開発実績です。',
              'items': ({'slug': 'mistar',
                         'title': 'MISTAR',
                         'category': 'Web・モバイルアプリ',
                         'description': 'Webとモバイルの開発、地図機能、ユーザーインターフェースとアプリケーションサービスの連携を含むプロジェクトです。',
                         'technologies': ('React.js', 'Kotlin', '地図連携', 'REST API')},
                        {'slug': 'rdd-android-application',
                         'title': 'RDD Android Application',
                         'category': 'Androidアプリ',
                         'description': 'KotlinとJetpack '
                                        'Composeを使用し、構造的で再利用しやすいモダンなUIを重視して開発したAndroidアプリです。',
                         'technologies': ('Kotlin', 'Jetpack Compose', 'Android')},
                        {'slug': 'laboratory-access-management',
                         'title': 'Laboratory Access Management',
                         'category': 'IoT・組み込みシステム',
                         'description': 'ソフトウェアとハードウェアを組み合わせ、研究室への入退室監視と自動化を支援するプロジェクトです。',
                         'technologies': ('Arduino', 'C++', 'センサー連携')})},
 'final_project': {'heading': '卒業制作',
                   'title': '布柄自動分類アプリケーション',
                   'description': 'Institut Teknologi '
                                  'Bandungで3人チームとして取り組みました。チームリーダーとしてAndroidアプリとフロントエンドを担当し、布柄の分類結果をアプリへ統合する作業を調整しました。',
                   'facts': ('Institut Teknologi Bandung',
                             '3人チーム',
                             'チームリーダー',
                             'Android・フロントエンド担当')},
 'skills': {'heading': '技術スキル',
            'groups': ({'title': 'フロントエンド開発',
                        'items': ('React.js',
                                  'JavaScript',
                                  'TypeScript',
                                  'Next.js',
                                  'Redux',
                                  'Zustand',
                                  'React Query',
                                  'Axios',
                                  'HTML',
                                  'CSS',
                                  'Tailwind CSS',
                                  'Material UI',
                                  'Ant Design',
                                  'Jest')},
                       {'title': 'モバイル開発',
                        'items': ('Kotlin', 'Jetpack Compose', 'Android', 'React Native基礎')},
                       {'title': 'バックエンド・アーキテクチャ',
                        'items': ('Node.js',
                                  'NestJS',
                                  'Hapi.js',
                                  'REST API連携',
                                  'Java Spring Boot基礎',
                                  'マイクロフロントエンド',
                                  'Module Federation',
                                  'Webpack')},
                       {'title': '開発ツール・品質',
                        'items': ('Git',
                                  'GitHub Actions',
                                  'Docker',
                                  'Figma',
                                  '単体テスト',
                                  'コードレビュー',
                                  'デバッグ')}),
            'learning': {'label': '現在学習中',
                         'description': '現在の専門分野としてではなく、今後のキャリア形成に向けて継続的に学んでいる技術です。',
                         'items': ('Python',
                                   'Computer Vision',
                                   'YOLO',
                                   'TensorFlow',
                                   'ROS',
                                   'C++',
                                   'SLAM',
                                   'LiDAR',
                                   '3D Camera',
                                   'Autonomous Mobile Robots')}},
 'education': {'heading': '学歴',
               'institution': 'Institut Teknologi Bandung',
               'program': 'コンピュータサイエンス／情報学',
               'graduation': '2023年卒業',
               'description': 'ソフトウェア工学、コンピュータサイエンスの基礎、アプリケーション開発を学び、布柄自動分類アプリケーションのチーム卒業制作に取り組みました。'},
 'career': {'heading': '目指している方向',
            'description': 'ソフトウェアエンジニアリングの経験を、AI、コンピュータビジョン、自律ロボティクスへつなげたいと考えています。Webやモバイルだけでなく、カメラ、センサー、機械、実環境と連携するソフトウェアの開発に関心があります。',
            'topics': ('AI Camera', 'AMR', 'ROS', 'SLAM')},
 'contact': {'heading': '価値あるものを、一緒につくりませんか',
             'description': 'ソフトウェアエンジニアリング、Web開発、インテリジェントアプリケーション、コンピュータビジョン、ロボティクスに関する機会や協業を歓迎しています。'}}
