from __future__ import annotations


AUTH_UI = {
    "id": {
        "skip": "Lewati ke konten utama",
        "login": "Login",
        "login_heading": "Login Admin",
        "login_intro": "Masuk untuk mengelola konten portofolio.",
        "email": "Email",
        "password": "Password",
        "invalid_credentials": "Email atau password tidak valid.",
        "required_fields": "Email dan password wajib diisi.",
        "csrf_error": "Permintaan tidak valid. Muat ulang halaman dan coba lagi.",
        "rate_limited": "Terlalu banyak percobaan login. Coba lagi nanti.",
        "session_expired": "Session berakhir. Silakan login kembali.",
        "dashboard": "Dashboard",
        "signed_in_as": "Login sebagai",
        "logout": "Logout",
        "language": "Bahasa",
        "apply": "Terapkan",
        "management": "Menu pengelolaan",
        "home_management": "Home Management",
        "project_management": "Project Management",
        "blog_management": "Blog Management",
        "cv_management": "CV Management",
        "api_management": "API Management",
        "placeholder": "Belum tersedia pada tahap autentikasi ini.",
        "footer": "Muhammad Rizal Muhaimin — Software Engineer.",
    },
    "en": {
        "skip": "Skip to main content",
        "login": "Log in",
        "login_heading": "Admin login",
        "login_intro": "Sign in to manage portfolio content.",
        "email": "Email",
        "password": "Password",
        "invalid_credentials": "Invalid email or password.",
        "required_fields": "Email and password are required.",
        "csrf_error": "The request is invalid. Reload the page and try again.",
        "rate_limited": "Too many login attempts. Try again later.",
        "session_expired": "Your session has expired. Please log in again.",
        "dashboard": "Dashboard",
        "signed_in_as": "Signed in as",
        "logout": "Log out",
        "language": "Language",
        "apply": "Apply",
        "management": "Management menu",
        "home_management": "Home Management",
        "project_management": "Project Management",
        "blog_management": "Blog Management",
        "cv_management": "CV Management",
        "api_management": "API Management",
        "placeholder": "Not available in this authentication phase.",
        "footer": "Muhammad Rizal Muhaimin — Software Engineer.",
    },
    "ja": {
        "skip": "メインコンテンツへ移動",
        "login": "ログイン",
        "login_heading": "管理者ログイン",
        "login_intro": "ポートフォリオのコンテンツを管理するためにログインしてください。",
        "email": "メールアドレス",
        "password": "パスワード",
        "invalid_credentials": "メールアドレスまたはパスワードが正しくありません。",
        "required_fields": "メールアドレスとパスワードを入力してください。",
        "csrf_error": "リクエストが無効です。ページを再読み込みして再試行してください。",
        "rate_limited": "ログイン試行回数が多すぎます。しばらくしてから再試行してください。",
        "session_expired": "セッションの有効期限が切れました。再度ログインしてください。",
        "dashboard": "ダッシュボード",
        "signed_in_as": "ログイン中",
        "logout": "ログアウト",
        "language": "言語",
        "apply": "適用",
        "management": "管理メニュー",
        "home_management": "ホーム管理",
        "project_management": "プロジェクト管理",
        "blog_management": "ブログ管理",
        "cv_management": "CV管理",
        "api_management": "API管理",
        "placeholder": "この認証フェーズではまだ利用できません。",
        "footer": "Muhammad Rizal Muhaimin — Software Engineer.",
    },
}


def auth_ui(language: str) -> dict[str, str]:
    return AUTH_UI[language]

